### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Moanrisy** [abdelaziz321/Agenda-To-do#6]
Hi

I'm using your code to complete final task in  my course. Course how to testing software, did you have any requirements for this code?

**Comment by abdelaziz321** [comment]
Hi @asamsulfat ,
I built this app just for learning purpose.
but i used this text file.
[Agenda-To-do.txt](https://github.com/abdelaziz321/Agenda-To-do/files/2016800/Agenda-To-do.txt)
Hope this helps.

**Comment by Moanrisy** [comment]
Thank you very much, my lecture not accepting our 'blackbox testing' because we test your code not from requirement.

But it actually make sense, how can you do blackbox testing without requirement.

Thanks again, your app so good, especially the UI. (:+1:
